-- 洛书图一：row_key=地支, col_key=天干 (120条)
INSERT INTO he_luo_lookup (matrix_code, row_key, col_key, value) VALUES
('luoshu_stem', '亥', '甲', 3), ('luoshu_stem', '亥', '乙', 3), ('luoshu_stem', '亥', '丙', 9), ('luoshu_stem', '亥', '丁', 9), ('luoshu_stem', '亥', '戊', 5), ('luoshu_stem', '亥', '己', 0), ('luoshu_stem', '亥', '庚', 7), ('luoshu_stem', '亥', '辛', 7), ('luoshu_stem', '亥', '壬', 1), ('luoshu_stem', '亥', '癸', 1),
('luoshu_stem', '子', '甲', 4), ('luoshu_stem', '子', '乙', 4), ('luoshu_stem', '子', '丙', 0), ('luoshu_stem', '子', '丁', 0), ('luoshu_stem', '子', '戊', 6), ('luoshu_stem', '子', '己', 1), ('luoshu_stem', '子', '庚', 8), ('luoshu_stem', '子', '辛', 8), ('luoshu_stem', '子', '壬', 2), ('luoshu_stem', '子', '癸', 2),
('luoshu_stem', '丑', '甲', 5), ('luoshu_stem', '丑', '乙', 5), ('luoshu_stem', '丑', '丙', 1), ('luoshu_stem', '丑', '丁', 1), ('luoshu_stem', '丑', '戊', 7), ('luoshu_stem', '丑', '己', 2), ('luoshu_stem', '丑', '庚', 9), ('luoshu_stem', '丑', '辛', 9), ('luoshu_stem', '丑', '壬', 3), ('luoshu_stem', '丑', '癸', 3),
('luoshu_stem', '寅', '甲', 6), ('luoshu_stem', '寅', '乙', 6), ('luoshu_stem', '寅', '丙', 2), ('luoshu_stem', '寅', '丁', 2), ('luoshu_stem', '寅', '戊', 8), ('luoshu_stem', '寅', '己', 3), ('luoshu_stem', '寅', '庚', 0), ('luoshu_stem', '寅', '辛', 0), ('luoshu_stem', '寅', '壬', 4), ('luoshu_stem', '寅', '癸', 4),
('luoshu_stem', '卯', '甲', 7), ('luoshu_stem', '卯', '乙', 7), ('luoshu_stem', '卯', '丙', 3), ('luoshu_stem', '卯', '丁', 3), ('luoshu_stem', '卯', '戊', 9), ('luoshu_stem', '卯', '己', 4), ('luoshu_stem', '卯', '庚', 1), ('luoshu_stem', '卯', '辛', 1), ('luoshu_stem', '卯', '壬', 5), ('luoshu_stem', '卯', '癸', 5),
('luoshu_stem', '辰', '甲', 8), ('luoshu_stem', '辰', '乙', 8), ('luoshu_stem', '辰', '丙', 4), ('luoshu_stem', '辰', '丁', 4), ('luoshu_stem', '辰', '戊', 0), ('luoshu_stem', '辰', '己', 5), ('luoshu_stem', '辰', '庚', 2), ('luoshu_stem', '辰', '辛', 2), ('luoshu_stem', '辰', '壬', 6), ('luoshu_stem', '辰', '癸', 6),
('luoshu_stem', '巳', '甲', 9), ('luoshu_stem', '巳', '乙', 9), ('luoshu_stem', '巳', '丙', 5), ('luoshu_stem', '巳', '丁', 5), ('luoshu_stem', '巳', '戊', 1), ('luoshu_stem', '巳', '己', 6), ('luoshu_stem', '巳', '庚', 3), ('luoshu_stem', '巳', '辛', 3), ('luoshu_stem', '巳', '壬', 7), ('luoshu_stem', '巳', '癸', 7),
('luoshu_stem', '午', '甲', 0), ('luoshu_stem', '午', '乙', 0), ('luoshu_stem', '午', '丙', 6), ('luoshu_stem', '午', '丁', 6), ('luoshu_stem', '午', '戊', 2), ('luoshu_stem', '午', '己', 7), ('luoshu_stem', '午', '庚', 4), ('luoshu_stem', '午', '辛', 4), ('luoshu_stem', '午', '壬', 8), ('luoshu_stem', '午', '癸', 8),
('luoshu_stem', '未', '甲', 1), ('luoshu_stem', '未', '乙', 1), ('luoshu_stem', '未', '丙', 7), ('luoshu_stem', '未', '丁', 7), ('luoshu_stem', '未', '戊', 3), ('luoshu_stem', '未', '己', 8), ('luoshu_stem', '未', '庚', 5), ('luoshu_stem', '未', '辛', 5), ('luoshu_stem', '未', '壬', 9), ('luoshu_stem', '未', '癸', 9),
('luoshu_stem', '申', '甲', 2), ('luoshu_stem', '申', '乙', 2), ('luoshu_stem', '申', '丙', 8), ('luoshu_stem', '申', '丁', 8), ('luoshu_stem', '申', '戊', 4), ('luoshu_stem', '申', '己', 9), ('luoshu_stem', '申', '庚', 6), ('luoshu_stem', '申', '辛', 6), ('luoshu_stem', '申', '壬', 0), ('luoshu_stem', '申', '癸', 0),
('luoshu_stem', '酉', '甲', 3), ('luoshu_stem', '酉', '乙', 3), ('luoshu_stem', '酉', '丙', 9), ('luoshu_stem', '酉', '丁', 9), ('luoshu_stem', '酉', '戊', 5), ('luoshu_stem', '酉', '己', 0), ('luoshu_stem', '酉', '庚', 7), ('luoshu_stem', '酉', '辛', 7), ('luoshu_stem', '酉', '壬', 1), ('luoshu_stem', '酉', '癸', 1),
('luoshu_stem', '戌', '甲', 4), ('luoshu_stem', '戌', '乙', 4), ('luoshu_stem', '戌', '丙', 0), ('luoshu_stem', '戌', '丁', 0), ('luoshu_stem', '戌', '戊', 6), ('luoshu_stem', '戌', '己', 1), ('luoshu_stem', '戌', '庚', 8), ('luoshu_stem', '戌', '辛', 8), ('luoshu_stem', '戌', '壬', 2), ('luoshu_stem', '戌', '癸', 2);

-- 洛书图二：row_key=地支(行), col_key=地支(列) (144条)
INSERT INTO he_luo_lookup (matrix_code, row_key, col_key, value) VALUES
('luoshu_branch', '亥', '子', 1), ('luoshu_branch', '亥', '丑', 8), ('luoshu_branch', '亥', '寅', 8), ('luoshu_branch', '亥', '卯', 3), ('luoshu_branch', '亥', '辰', 4), ('luoshu_branch', '亥', '巳', 4), ('luoshu_branch', '亥', '午', 9), ('luoshu_branch', '亥', '未', 2), ('luoshu_branch', '亥', '申', 2), ('luoshu_branch', '亥', '酉', 7), ('luoshu_branch', '亥', '戌', 6), ('luoshu_branch', '亥', '亥', 6),
('luoshu_branch', '子', '子', 2), ('luoshu_branch', '子', '丑', 9), ('luoshu_branch', '子', '寅', 9), ('luoshu_branch', '子', '卯', 4), ('luoshu_branch', '子', '辰', 5), ('luoshu_branch', '子', '巳', 5), ('luoshu_branch', '子', '午', 0), ('luoshu_branch', '子', '未', 3), ('luoshu_branch', '子', '申', 3), ('luoshu_branch', '子', '酉', 8), ('luoshu_branch', '子', '戌', 7), ('luoshu_branch', '子', '亥', 7),
('luoshu_branch', '丑', '子', 3), ('luoshu_branch', '丑', '丑', 0), ('luoshu_branch', '丑', '寅', 0), ('luoshu_branch', '丑', '卯', 5), ('luoshu_branch', '丑', '辰', 6), ('luoshu_branch', '丑', '巳', 6), ('luoshu_branch', '丑', '午', 1), ('luoshu_branch', '丑', '未', 4), ('luoshu_branch', '丑', '申', 4), ('luoshu_branch', '丑', '酉', 9), ('luoshu_branch', '丑', '戌', 8), ('luoshu_branch', '丑', '亥', 8),
('luoshu_branch', '寅', '子', 4), ('luoshu_branch', '寅', '丑', 1), ('luoshu_branch', '寅', '寅', 1), ('luoshu_branch', '寅', '卯', 6), ('luoshu_branch', '寅', '辰', 7), ('luoshu_branch', '寅', '巳', 7), ('luoshu_branch', '寅', '午', 2), ('luoshu_branch', '寅', '未', 5), ('luoshu_branch', '寅', '申', 5), ('luoshu_branch', '寅', '酉', 0), ('luoshu_branch', '寅', '戌', 9), ('luoshu_branch', '寅', '亥', 9),
('luoshu_branch', '卯', '子', 5), ('luoshu_branch', '卯', '丑', 2), ('luoshu_branch', '卯', '寅', 2), ('luoshu_branch', '卯', '卯', 7), ('luoshu_branch', '卯', '辰', 8), ('luoshu_branch', '卯', '巳', 8), ('luoshu_branch', '卯', '午', 3), ('luoshu_branch', '卯', '未', 6), ('luoshu_branch', '卯', '申', 6), ('luoshu_branch', '卯', '酉', 1), ('luoshu_branch', '卯', '戌', 0), ('luoshu_branch', '卯', '亥', 0),
('luoshu_branch', '辰', '子', 6), ('luoshu_branch', '辰', '丑', 3), ('luoshu_branch', '辰', '寅', 3), ('luoshu_branch', '辰', '卯', 8), ('luoshu_branch', '辰', '辰', 9), ('luoshu_branch', '辰', '巳', 9), ('luoshu_branch', '辰', '午', 4), ('luoshu_branch', '辰', '未', 7), ('luoshu_branch', '辰', '申', 7), ('luoshu_branch', '辰', '酉', 2), ('luoshu_branch', '辰', '戌', 1), ('luoshu_branch', '辰', '亥', 1),
('luoshu_branch', '巳', '子', 7), ('luoshu_branch', '巳', '丑', 4), ('luoshu_branch', '巳', '寅', 4), ('luoshu_branch', '巳', '卯', 9), ('luoshu_branch', '巳', '辰', 0), ('luoshu_branch', '巳', '巳', 0), ('luoshu_branch', '巳', '午', 5), ('luoshu_branch', '巳', '未', 8), ('luoshu_branch', '巳', '申', 8), ('luoshu_branch', '巳', '酉', 3), ('luoshu_branch', '巳', '戌', 2), ('luoshu_branch', '巳', '亥', 2),
('luoshu_branch', '午', '子', 8), ('luoshu_branch', '午', '丑', 5), ('luoshu_branch', '午', '寅', 5), ('luoshu_branch', '午', '卯', 0), ('luoshu_branch', '午', '辰', 1), ('luoshu_branch', '午', '巳', 1), ('luoshu_branch', '午', '午', 6), ('luoshu_branch', '午', '未', 9), ('luoshu_branch', '午', '申', 9), ('luoshu_branch', '午', '酉', 4), ('luoshu_branch', '午', '戌', 3), ('luoshu_branch', '午', '亥', 3),
('luoshu_branch', '未', '子', 9), ('luoshu_branch', '未', '丑', 6), ('luoshu_branch', '未', '寅', 6), ('luoshu_branch', '未', '卯', 1), ('luoshu_branch', '未', '辰', 2), ('luoshu_branch', '未', '巳', 2), ('luoshu_branch', '未', '午', 7), ('luoshu_branch', '未', '未', 0), ('luoshu_branch', '未', '申', 0), ('luoshu_branch', '未', '酉', 5), ('luoshu_branch', '未', '戌', 4), ('luoshu_branch', '未', '亥', 4),
('luoshu_branch', '申', '子', 0), ('luoshu_branch', '申', '丑', 7), ('luoshu_branch', '申', '寅', 7), ('luoshu_branch', '申', '卯', 2), ('luoshu_branch', '申', '辰', 3), ('luoshu_branch', '申', '巳', 3), ('luoshu_branch', '申', '午', 8), ('luoshu_branch', '申', '未', 1), ('luoshu_branch', '申', '申', 1), ('luoshu_branch', '申', '酉', 6), ('luoshu_branch', '申', '戌', 5), ('luoshu_branch', '申', '亥', 5),
('luoshu_branch', '酉', '子', 1), ('luoshu_branch', '酉', '丑', 8), ('luoshu_branch', '酉', '寅', 8), ('luoshu_branch', '酉', '卯', 3), ('luoshu_branch', '酉', '辰', 4), ('luoshu_branch', '酉', '巳', 4), ('luoshu_branch', '酉', '午', 9), ('luoshu_branch', '酉', '未', 2), ('luoshu_branch', '酉', '申', 2), ('luoshu_branch', '酉', '酉', 7), ('luoshu_branch', '酉', '戌', 6), ('luoshu_branch', '酉', '亥', 6),
('luoshu_branch', '戌', '子', 2), ('luoshu_branch', '戌', '丑', 9), ('luoshu_branch', '戌', '寅', 9), ('luoshu_branch', '戌', '卯', 4), ('luoshu_branch', '戌', '辰', 5), ('luoshu_branch', '戌', '巳', 5), ('luoshu_branch', '戌', '午', 0), ('luoshu_branch', '戌', '未', 3), ('luoshu_branch', '戌', '申', 3), ('luoshu_branch', '戌', '酉', 8), ('luoshu_branch', '戌', '戌', 7), ('luoshu_branch', '戌', '亥', 7);
